## Settings
title: Kode Kata
owner: "taufardh"
url: "https://taufardh.github.io"
baseurl: "/kode"
permalink: /:title/
description: "simple blog pages"
markdown: kramdown
webrick:
  headers:
    Access-Control-Allow-Origin: "*"
## Global Variables
email: "ardhwood@gmail.com"
github: "taufardh"
# path to: css/, fonts/, img/ and js/
assets_path: "/assets" # i.e. "/assets" 
statement: "taufardh, All Rights Reserved"
# default max toc levels: 1 - 6 (h1 - h6)
toc_level: 3
# texts randomly displayed in background
#bgtext: "αβγδεζηθικλμνξοπρστυφχψω∷∫∮∝∞∧∨∑∏∪∩∈∵∴⊥‖∠⌒⊙≌√"
bgtext: "Semangat Sukses Berhasil Juara Senyum Indah Bahagia"
